SELECT FIRST_NAME FROM worker; 
SELECT upper(FIRST_NAME) FROM worker ; 
SELECT distinct DEPARTMENT FROM worker;
SELECT   SUBSTRING(FIRST_NAME, 1, 3)
FROM worker;

SELECT *
FROM worker 
ORDER BY FIRST_NAME ASC;

SELECT *
FROM worker 
ORDER BY FIRST_NAME ASC , DEPARTMENT DESC


SELECT * 
FROM worker
WHERE FIRST_NAME='Viktoria' OR FIRST_NAME='Alex';

SELECT * 
FROM worker
WHERE LAST_NAME !='Smith' AND LAST_NAME !='Maxwell';

SELECT * 
FROM worker
WHERE DEPARTMENT ='Admin';

SELECT *
FROM worker
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM worker
WHERE LAST_NAME LIKE '%h%';


SELECT *
FROM worker
WHERE SALARY BETWEEN 100000  AND 500000;






